# Generated by Django 5.2.1 on 2025-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_remove_book_description_book_content_book_cover_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content',
        ),
        migrations.AddField(
            model_name='book',
            name='content_file',
            field=models.FilePathField(blank=True, null=True, path='datasets/gutenberg_books/'),
        ),
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(choices=[('BX', 'Book-Crossing'), ('GUT', 'Gutenberg')], default='BX', max_length=10),
        ),
    ]
