# Generated by Django 5.2.1 on 2025-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_remove_book_content_book_content_file_book_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='content_file',
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
