# Generated by Django 5.2.1 on 2025-10-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_remove_book_content_book_file_path_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
