# Generated by Django 5.2.1 on 2025-10-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_alter_book_options_book_description_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
