# Generated by Django 5.2.1 on 2025-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_userbook_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbook',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
