# Generated by Django 5.2.1 on 2025-10-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_book_genre_userbook_sentiment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='read_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
