# Generated by Django 5.2.1 on 2025-10-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0011_book_total_pages_downloadlog_readinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='last_page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
