# Generated by Django 5.2.1 on 2026-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0013_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
