# Generated by Django 5.2.1 on 2026-02-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0014_userbook_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='is_favorite',
        ),
    ]
