# Generated by Django 5.2.1 on 2025-12-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone_number_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='recommender/img/profile.jpg', upload_to='profile_images/'),
        ),
    ]
